# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-22 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('testModule', models.CharField(max_length=500)),
                ('testExplain', models.CharField(max_length=500)),
                ('wantResult', models.CharField(max_length=500)),
                ('testResult', models.CharField(max_length=500)),
                ('testTime', models.CharField(max_length=500)),
            ],
        ),
    ]
