# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-26 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='testR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=10)),
                ('time', models.TimeField()),
            ],
        ),
    ]
